version: '3.8'

services:
  existing-service:
    # Your existing service configuration
    # Make sure it's not publishing port 80 directly

  sharkpool-monitor:
    build: .
    expose:
      - "7681"
    command: ttyd -p 7681 python run.py

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - existing-service
      - sharkpool-monitor