version: '3.8'

services:
  sharkpool-monitor:
    build: .
    expose:
      - "7681"
    command: ttyd -p 7681 python run.py

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Changed to 8080 to avoid conflicts with existing services
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sharkpool-monitor